<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-I12I50L" name="eodValidations.Testing2" tests="10" failures="0" timestamp="17 Oct 2020 04:26:15 GMT" time="0.061" errors="1">
  <testcase name="Test2" time="0.003" classname="eodValidations.Testing2">
    <error type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at eodValidations.Testing2.Test2(Testing2.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.004" classname="eodValidations.Testing2"/>
  <testcase name="Test8" time="0.004" classname="eodValidations.Testing2"/>
  <testcase name="Test4" time="0.010" classname="eodValidations.Testing2"/>
  <testcase name="Test10" time="0.015" classname="eodValidations.Testing2"/>
  <testcase name="Test5" time="0.003" classname="eodValidations.Testing2"/>
  <testcase name="Test7" time="0.004" classname="eodValidations.Testing2"/>
  <testcase name="Test9" time="0.011" classname="eodValidations.Testing2"/>
  <testcase name="Test6" time="0.003" classname="eodValidations.Testing2"/>
  <testcase name="Test1" time="0.004" classname="eodValidations.Testing2"/>
</testsuite> <!-- eodValidations.Testing2 -->
